import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import Post from '../../../components/post/Post';

import prisma from '../../../lib/prisma'

import { useEffect } from "react"
import { useUsers } from '../../../context/UsersContext';
import { useFilter } from '../../../context/FilterContext';

export const getServerSideProps: GetServerSideProps = async ({ params, query }) => {
  const { tags: rawTags } = query
  const numPerPage = 20
  const pageOffset = Number((Math.max(Number(params?.page) - 1, 0)) * numPerPage)
  const tags = rawTags ? String(rawTags).toLowerCase().split(" ").filter((tag: string) => tag.trim() !== "").map((tag: string) => tag.replace(/[^\w-]+/g, '')) : []

  const feedQ = await prisma.post.findMany({
    where: { published: true, imagePending: false, ...(rawTags ? { tags: { some: { name: { in: tags } } } } : {}) },
    include: {
      author: { select: { id: true }, },
      tags: true,
      shares: true,
      likes: true
    },
    orderBy: { createdAt: "desc" },
    skip: pageOffset,
    take: numPerPage
  });
  // doing 2 queries...........
  const feedQ_count = await prisma.post.findMany({
    where: { published: true, imagePending: false, ...(rawTags ? { tags: { some: { name: { in: tags } } } } : {}) },
    select: { id:true }
  })
  const feed = feedQ.map((data: any) => ({
    ...data,
    tags: data.tags.map((tag: any) => tag.name),
  }))
  // recommended section here when you have enough posts to test it out properly
  return {
    props: { 
      feed: JSON.parse(JSON.stringify(feed)),
      pageCount: feedQ.length,
      fullCount: feedQ_count.length
     },
  };
};

const Page = ({ feed, pageCount, fullCount, maxPage }: { feed: any[], pageCount: number, fullCount: number, maxPage: number }) => {
  const { cacheProfileDataForUser } = useUsers()
  const { searchTags, setPageCount, setFullCount, setMaxPage } = useFilter()

  useEffect(() => {
    if (!feed) return
    feed.forEach((post: any) => cacheProfileDataForUser(post.author.id))
  }, [feed])

  useEffect(() => {
    setFullCount(fullCount)
    setPageCount(pageCount)
    setMaxPage(maxPage)
  }, [feed])

  return (
    <div className='flex flex-col justify-between w-full mx-auto p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-full'>
        {feed.map((post: any, i:number) => <Post reverse={Boolean(i % 2)} key={post.id} post={post} />)}
      </div>
    </div>
  )
}

export default Page
