import type { GetStaticProps } from 'next'
import Head from 'next/head'
import Post from '../components/Post';

import prisma from '../lib/prisma'

export const getStaticProps: GetStaticProps = async () => {
  const q = await prisma.post.findMany({
    where: { published: true, imagePending:false },
    include: {
      author: {
        select: { name: true, image: true, id:true },
      },
      tags: true,
      shares: true,
      likes: true
    },
  });
  const feed = q.map((data: any) => ({
    ...data,
    tags: data.tags.map((tag: any) => tag.name),
    shares: data.shares.map((share:any) => share.userId),
    likes: data.likes.map((share:any) => share.userId),
  }))
  return {
    props: { feed: JSON.parse(JSON.stringify(feed)) },
    revalidate: 10,
  };
};

const Home = ({ feed }: { feed: any }) => {
  return (
    <div className='flex justify-between w-full mx-auto p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-full gap-2'>
        {feed.map((post: any) => <Post key={post.id} post={post} />)}
      </div>
    </div>
  )
}

export default Home
